
package br.edu.unirn.impls;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.edu.unirn.interfaces.Animal;
import br.edu.unirn.interfaces.ObjectFactory;
import br.edu.unirn.interfaces.Pessoa;
import br.edu.unirn.interfaces.Relacao;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrudWS", targetNamespace = "http://interfaces.unirn.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrudWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.edu.unirn.interfaces.Relacao>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCompletaRelacao", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaRelacao")
    @ResponseWrapper(localName = "listaCompletaRelacaoResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaRelacaoResponse")
    public List<Relacao> listaCompletaRelacao();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePessoa", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeletePessoa")
    @ResponseWrapper(localName = "deletePessoaResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeletePessoaResponse")
    public void deletePessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePessoa", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdatePessoa")
    @ResponseWrapper(localName = "updatePessoaResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdatePessoaResponse")
    public void updatePessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRelacao", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeleteRelacao")
    @ResponseWrapper(localName = "deleteRelacaoResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeleteRelacaoResponse")
    public void deleteRelacao(
        @WebParam(name = "arg0", targetNamespace = "")
        Relacao arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateRelacao", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdateRelacao")
    @ResponseWrapper(localName = "updateRelacaoResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdateRelacaoResponse")
    public void updateRelacao(
        @WebParam(name = "arg0", targetNamespace = "")
        Relacao arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.unirn.interfaces.Pessoa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCompletaPessoa", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaPessoa")
    @ResponseWrapper(localName = "listaCompletaPessoaResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaPessoaResponse")
    public List<Pessoa> listaCompletaPessoa();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarPessoa", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarPessoa")
    @ResponseWrapper(localName = "cadastrarPessoaResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarPessoaResponse")
    public void cadastrarPessoa(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.unirn.interfaces.Animal>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaCompletaAnimal", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaAnimal")
    @ResponseWrapper(localName = "listaCompletaAnimalResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.ListaCompletaAnimalResponse")
    public List<Animal> listaCompletaAnimal();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarAnimal", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarAnimal")
    @ResponseWrapper(localName = "cadastrarAnimalResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarAnimalResponse")
    public void cadastrarAnimal(
        @WebParam(name = "arg0", targetNamespace = "")
        Animal arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarRelacao", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarRelacao")
    @ResponseWrapper(localName = "cadastrarRelacaoResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.CadastrarRelacaoResponse")
    public void cadastrarRelacao(
        @WebParam(name = "arg0", targetNamespace = "")
        Relacao arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateAnimal", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdateAnimal")
    @ResponseWrapper(localName = "updateAnimalResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.UpdateAnimalResponse")
    public void updateAnimal(
        @WebParam(name = "arg0", targetNamespace = "")
        Animal arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAnimal", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeleteAnimal")
    @ResponseWrapper(localName = "deleteAnimalResponse", targetNamespace = "http://interfaces.unirn.edu.br/", className = "br.edu.unirn.interfaces.DeleteAnimalResponse")
    public void deleteAnimal(
        @WebParam(name = "arg0", targetNamespace = "")
        Animal arg0);

}
