
package br.edu.unirn.impls;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WServices", targetNamespace = "http://impls.unirn.edu.br/", wsdlLocation = "http://localhost:8080/services/WServices?wsdl")
public class WServices
    extends Service
{

    private final static URL WSERVICES_WSDL_LOCATION;
    private final static WebServiceException WSERVICES_EXCEPTION;
    private final static QName WSERVICES_QNAME = new QName("http://impls.unirn.edu.br/", "WServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/WServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSERVICES_WSDL_LOCATION = url;
        WSERVICES_EXCEPTION = e;
    }

    public WServices() {
        super(__getWsdlLocation(), WSERVICES_QNAME);
    }

    public WServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSERVICES_QNAME, features);
    }

    public WServices(URL wsdlLocation) {
        super(wsdlLocation, WSERVICES_QNAME);
    }

    public WServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSERVICES_QNAME, features);
    }

    public WServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrudWS
     */
    @WebEndpoint(name = "CrudWSImplPort")
    public CrudWS getCrudWSImplPort() {
        return super.getPort(new QName("http://impls.unirn.edu.br/", "CrudWSImplPort"), CrudWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrudWS
     */
    @WebEndpoint(name = "CrudWSImplPort")
    public CrudWS getCrudWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impls.unirn.edu.br/", "CrudWSImplPort"), CrudWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSERVICES_EXCEPTION!= null) {
            throw WSERVICES_EXCEPTION;
        }
        return WSERVICES_WSDL_LOCATION;
    }

}
